import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "@page_styles/Home.module.scss";
import Container from "@/design_systems/mainds/components/Container";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container type="screen-md">
          <p>Default template removed.</p>
        </Container>
      </main>
    </div>
  );
};

export default Home;
