import type { NextPage } from "next";
import Head from "next/head";
import styles from "@page_styles/Home.module.scss";
import DSStyles from "@mainds/styles/mainds.module.scss";
import AppLink from "@/components/AppLink";
import Container from "@/design_systems/mainds/components/Container";
import ProjectDisplay from "@/components/ProjectDisplay";
import { projects } from "@/data/projects";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container type="screen-sm">
          <div style={{ marginBottom: "64px" }}></div>
          {/* <div style={{ marginBottom: "128px" }}></div> */}
          <p className={styles["lead-paragraph"]}>Ayo Akindele</p>
          <p className={styles["paragraph"]}>
            Building interfaces to solve design problems. Working primarily with
            React, Next.js, and Typescript. BSc Computing Science from the
            University of Alberta.
          </p>
          <div className={styles["link-container"]}>
            <p className={styles["paragraph"]}>
              <AppLink
                href="/resume.pdf"
                className={DSStyles["link-text"]}
                openInNewTab
              >
                Resume
              </AppLink>
            </p>
            <p className={styles["paragraph"]}>
              <AppLink
                href="https://github.com/aakindel"
                className={DSStyles["link-text"]}
                openInNewTab
              >
                Github
              </AppLink>
            </p>
          </div>
          <p className={styles["section-header"]}>Projects</p>
        </Container>
        <Container type="screen-md">
          {projects.map((project, index) => {
            return <ProjectDisplay key={index} project={project} />;
          })}
        </Container>
      </main>
    </div>
  );
};

export default Home;
